
services:
  spark-etl:
    build: .
    container_name: spark_auditoria_app
    volumes:
      # Montar las subcarpetas de src/ para persistencia de datos local
      - ./src/db:/app/src/db
      - ./src/sources:/app/src/sources
      - ./src/xlsx:/app/src/xlsx
      - ./src/static:/app/src/static
    environment:
      - PYTHONUNBUFFERED=1