name: Pipeline Big Data - EA2 Ingesta + Limpieza
 
on:
  push:
    branches: [ "main", "master" ]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

# Permite que el bot tenga acceso de escritura al repositorio
permissions:
  contents: write
 
jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
 
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
 
      - name: Instalar Dependencias
        run: |
         python -m pip install --upgrade pip
         pip install -r requirements.txt
 
      - name: Etapa 1 - Ingesta (extraccion desde el API)
        run: python main.py
 
      - name: Etapa 2 - Limpieza (lectura desde la nube simulada)
        run: python cleaning.py
 
      - name: Verificar artefactos
        run: |
          test -f src/xlsx/cleaned_data.xlsx && echo "Datos limpios OK"
          test -f src/static/auditoria/cleaning_report.txt && echo "Auditoria OK"
          cat src/static/auditoria/cleaning_report.txt
 
      - name: Publicar evidencias
        uses: actions/upload-artifact@v4
        with:
          name: evidencias-limpieza
          path: |
            src/db/ingestion.db
            src/xlsx/cleaned_data.xlsx
            src/static/auditoria/cleaning_report.txt
